development: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  host: localhost
  database: lambda_dev
  username: wengran
  password: Wwr1995@1206

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  database: lambda_test
  username: wengran
  password: 0

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
  username: wengran
  password: 0

staging: *deploy
